# Generated by Django 5.1.4 on 2024-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250)),
                ('webhook_url', models.URLField(max_length=250)),
                ('admin', models.IntegerField()),
            ],
        ),
    ]
