# Generated by Django 5.1.4 on 2024-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(default='token', max_length=250)),
                ('secret_key', models.CharField(default='secret_key', max_length=250)),
                ('webhook_url', models.URLField(default='https://api.telegram.org/', max_length=250)),
                ('admin', models.IntegerField(default=12345678)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
