# Generated by Django 5.1.4 on 2024-12-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='popularity_score',
        ),
    ]
