# Generated by Django 5.1.4 on 2024-12-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_carmodel_popularity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotconfiguration',
            name='webhook_url',
        ),
    ]
