# Generated by Django 5.1.4 on 2024-12-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_telegrambotconfiguration_webhook_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferred_language',
            new_name='language',
        ),
    ]
