# Generated by Django 5.1.4 on 2024-12-18 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_rename_preferred_language_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 12, 18, 13, 34, 28, 488762, tzinfo=datetime.timezone.utc), max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 12, 18, 13, 34, 33, 31618, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
